- name: ryu deployment
  hosts: all
  gather_facts: no
  become: True
  tasks:
    - name: install apt packages
      apt:
        update_cache: yes
        cache_valid_time: 3600
        pkg:
          - git
          - mininet
          - python-dev
          - python-setuptools
          - python3-pip
          - iptables
    - name: install ryu
      pip:
        name: ryu
      executable: pip3
    - name: install paramiko
      become: True
      pip:
        name: paramiko
    - name: install eventlet
      pip:
        name: eventlet==0.30.2
    - name: OpenVSwitch setup
      shell: "ovs-vsctl set-manager ptcp:6640"
#    - name: Forward port 179 to 30179
#      ansible.builtin.iptables:
#        table: nat
#        chain: OUTPUT
#        protocol: tcp
#        match: tcp
#        destination_port: 179
#        jump: REDIRECT
#        to_ports: 30179
