- name: Clone evpn-for-ovn
  hosts: all
  become: yes
  become_user: vagrant
  gather_facts: no
  tasks:
    - name: Clone devstack
      git:
        repo: https://github.com/romanspb80/evpn-for-ovn.git
        dest: /home/vagrant/evpn-for-ovn
        version: rework_the_project

- name: microstack install
  hosts: all
  become: yes
  become_user: root
  gather_facts: no
  tasks:
    - name: microstack install
      shell: snap install microstack --beta --devmode
    - name: Create openstack cluster
      shell: microstack init --auto --control
    - name: Create alias for microstack.ovs-vsctl
      shell: snap alias microstack.ovs-vsctl ovs-vsctl
    - name: Create alias for microstack.ovn-nbctl
      shell: snap alias microstack.ovn-nbctl ovn-nbctl
    - name: Create alias for microstack.rabbitmqctl
      shell: snap alias microstack.rabbitmqctl rabbitmqctl
    - name: Create alias for microstack.openstack
      shell: snap alias microstack.openstack openstack

- name: OpenVSwitch & OVN setup
  hosts: all
  become: yes
  become_user: root
  gather_facts: no
  tasks:
    - name: OVS setup
      shell: ovs-vsctl set-manager ptcp:6640
    - name: OVN setup
      shell: ovn-nbctl set-connection ptcp:6641:192.168.10.20

- name: Set RabbitMQ up
  hosts: all
  become: yes
  become_user: root
  gather_facts: no
  tasks:
    - name: Add RabbitMQ user
      shell: rabbitmqctl add_user stackrabbit secret
    - name: Set RabbitMQ permissions for user
      shell: rabbitmqctl set_permissions stackrabbit ".*" ".*" ".*"
    - name: Set RabbitMQ tag for user
      shell: rabbitmqctl set_user_tags stackrabbit administrator
    - name: Restart RabbitMQ
      shell: snap restart microstack.rabbitmq-server

- name: microk8s install & kubernetes cluster deployment
  hosts: all
  become: yes
  become_user: root
  gather_facts: no
  tasks:
    - name: microk8s install
      snap:
        name: microk8s
        classic: yes
        channel: 1.21/stable
    - name: Wait for microk8s to be ready
      shell: microk8s status --wait-ready
      changed_when: False
#    - name: set microk8s up
#      command: /home/vagrant/evpn-for-ovn/vagrant/synced_folders_k8s/setup_microk8s.sh
#      register: stdout
#    - debug:
#        var: stdout.stdout_lines
    - name: microk8s - enable dns ingress helm3
      raw: microk8s enable dns ingress helm3
    - name: Create alias for microk8s.kubectl
      shell: snap alias microk8s.kubectl kubectl
    - name: Create alias for microk8s.helm3
      shell: snap alias microk8s.helm3 helm3
    - name: kubernetes cluster deployment
      shell: helm3 install evpn-ovn /home/vagrant/evpn-for-ovn/vagrant/helm_chart/evpnOVN
