- name: ryu deployment
  hosts: all
  gather_facts: no
  tasks:
    - name: install apt packages
      apt:
        update_cache: yes
        cache_valid_time: 3600
        pkg:
          - git
          - mininet
          - python-dev
          - python-setuptools
          - python3-pip
          - iptables
      become: True
    - name: install ryu
      pip:
        name: ryu
    - name: openvswitch setup
      shell: ovs-vsctl set-manager ptcp:6640
      become: True
