- name: ryu deployment
  hosts: all
  gather_facts: no
  become: True
  tasks:
    - name: install apt packages
      apt:
        update_cache: yes
        cache_valid_time: 3600
        pkg:
          - mininet
          - python3-ryu
    - name: OpenVSwitch setup
      shell: "ovs-vsctl set-manager ptcp:6640"
