apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ .Values.api.name }}-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.api.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.name }}
    spec:
      containers:
      - name: {{ .Values.api.name }}
        image: {{ .Values.api.ReplicaSet.containers.image }}
        volumeMounts:
        - name: {{ .Values.common.configMap }}
          mountPath: /config
        ports:
        - containerPort: 5000
          name: http
        - containerPort: 22
          name: ssh
      volumes:
      - name: {{ .Values.common.configMap }}
        configMap:
          name: {{ .Values.common.configMap }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.api.name }}-ing
spec:
  rules:
  - host: {{ .Values.api.Ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.api.name }}-svc
            port:
              number: {{ .Values.api.Ingress.port }}
