apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ .Values.ovsdbAgent.name }}-ds
  labels:
    app: {{ .Values.ovsdbAgent.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.ovsdbAgent.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.ovsdbAgent.name }}
    spec:
      containers:
      - name: {{ .Values.ovsdbAgent.name }}
        image: {{ .Values.ovsdbAgent.ReplicaSet.containers.image }}
        volumeMounts:
        - name: {{ .Values.common.configMap }}
          mountPath: /config
      volumes:
      - name: {{ .Values.common.configMap }}
        configMap:
          name: {{ .Values.common.configMap }}
