apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}-svc
spec:
  ports:
  - port: {{ .Values.api.Ingress.port }}
    targetPort: http
  selector:
    app: evpn-api

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.externalServices.rabbitmq.name }}-svc
spec:
  ports:
  - name: {{ .Values.externalServices.rabbitmq.name }}
    protocol: TCP
    port: 5672
    nodePort: 0

---

apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.externalServices.rabbitmq.name }}-svc
subsets:
  - addresses:
    - ip: {{ .Values.externalServices.rabbitmq.Endpoints.ip }}
    ports:
    - name: {{ .Values.externalServices.rabbitmq.name }}
      port: 5672

---

apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.externalServices.bgp.name }}-svc
subsets:
  - addresses:
    - ip: {{ .Values.externalServices.bgp.Endpoints.ip }}
    ports:
    - name: {{ .Values.externalServices.bgp.name }}-remote
      port: 179

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.externalServices.ovsdb.name }}
spec:
  ports:
  - name: ovnnb
    protocol: TCP
    port: 6641
    targetPort: 6641
    nodePort: 0
  - name: ovs
    protocol: TCP
    port: 6640
    targetPort: 6640
    nodePort: 0

---

apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.externalServices.ovsdb.name }}
subsets:
  - addresses:
    - ip: {{ .Values.externalServices.ovsdb.Endpoints.ip }}
    ports:
    - name: ovnnb
      port: 6641
    - name: ovs
      port: 6640
